spring:
    application:
        name: movies-service
    profiles:
        active: local
restClient:
    moviesInfoUrl: http://${MOVIES_INFO_HOST:localhost}:8080/v1/movieinfos
    reviewsUrl: http://${MOVIES_REVIEWS_HOST:localhost}:8081/v1/reviews
server:
    port: 8082
