spring:
    application:
        name: movies-info-service
    profiles:
        active: local
---
spring:
    config:
        activate:
            on-profile:
                - local
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: 27017
            database: local
---
spring:
    config:
        activate:
            on-profile:
                - non-prod
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: 27017
            database: local
---
spring:
    config:
        activate:
            on-profile:
                - prod
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: 27017
            database: local