spring:
    application:
        name: movies-review-service
    profiles:
        active: local
---
spring:
    config:
        activate:
            on-profile:
                - local
    data:
        mongodb:
            host: ${MONGODB_HOST:localhost}
            port: 27017
            database: local
            
server:
    port: 8081
